// GENERATED by FOWC_publish on 2026-08-19. Do not edit by hand.
window.FOWC_DATA = {
  "meta": {
    "campaign": "Fundamentals of Welding Curriculum",
    "code": "EDU_1045",
    "year": 2026,
    "campaignStart": "2026-03-16",
    "campaignEnd": "2026-11-30",
    "landingPageLive": "2026-05-11",
    "dataThrough": "2026-08-19",
    "generated": "2026-08-19",
    "paidThrough": "2026-07-31",
    "mondayBoard": "https://aws-projects.monday.com/boards/18399502759",
    "landingPage": "https://www.aws.org/educators/welding-curriculum/",
    "landingPath": "/educators/welding-curriculum/",
    "formUrl": "https://app.hubspot.com/submissions/7723471/form/d73e472e-dfd2-42d3-a8a7-626af5df4590/performance",
    "formName": "Fundamentals of Welding Curriculum (FOWC) educator resources",
    "repo": "American-Welding-Society/reporting"
  },
  "summary": [
    {
      "channel": "Goal",
      "label": "Page Submissions",
      "value": 143,
      "fmt": "int",
      "sub": "2026 to date",
      "tier": "manual"
    },
    {
      "channel": "Website",
      "label": "Landing Sessions",
      "value": 14700,
      "fmt": "int",
      "sub": "all sources",
      "tier": "observed"
    },
    {
      "channel": "Paid Media",
      "label": "Spend",
      "value": 14225.73,
      "fmt": "money",
      "sub": "of $18,000 budgeted",
      "tier": "observed"
    },
    {
      "channel": "Paid Media",
      "label": "Clicks",
      "value": 19725,
      "fmt": "int",
      "sub": "3 platforms",
      "tier": "observed"
    },
    {
      "channel": "Email",
      "label": "Clicks",
      "value": 307,
      "fmt": "int",
      "sub": "2 sends of 4 planned",
      "tier": "observed"
    }
  ],
  "goal": {
    "target": 460,
    "baseline2025": 328,
    "primary": "Page submissions",
    "measures": [
      {
        "label": "Page submissions",
        "value": 143,
        "tier": "manual",
        "note": "Every submission on the landing page, including repeats and existing contacts."
      },
      {
        "label": "New contacts",
        "value": 49,
        "tier": "manual",
        "note": "Contacts whose first ever conversion was this form. A subset of submissions."
      }
    ]
  },
  "pacing": {
    "daysElapsed": 157,
    "daysTotal": 259,
    "budget": 18000,
    "spend": 14225.73,
    "goalActual": 143,
    "goalTarget": 460
  },
  "monthly": [
    {
      "m": "2026-01",
      "sessions": 177,
      "engaged": 124,
      "spend": 0,
      "submissions": 13,
      "partial": false
    },
    {
      "m": "2026-02",
      "sessions": 196,
      "engaged": 158,
      "spend": 0,
      "submissions": 10,
      "partial": false
    },
    {
      "m": "2026-03",
      "sessions": 223,
      "engaged": 159,
      "spend": 0,
      "submissions": 18,
      "partial": false
    },
    {
      "m": "2026-04",
      "sessions": 300,
      "engaged": 205,
      "spend": 0,
      "submissions": 18,
      "partial": false
    },
    {
      "m": "2026-05",
      "sessions": 3064,
      "engaged": 1893,
      "spend": 5039.17,
      "submissions": 33,
      "partial": false
    },
    {
      "m": "2026-06",
      "sessions": 6426,
      "engaged": 4195,
      "spend": 5033.83,
      "submissions": 32,
      "partial": false
    },
    {
      "m": "2026-07",
      "sessions": 3781,
      "engaged": 2181,
      "spend": 4152.73,
      "submissions": 11,
      "partial": false
    },
    {
      "m": "2026-08",
      "sessions": 533,
      "engaged": 206,
      "spend": null,
      "submissions": 8,
      "partial": true
    }
  ],
  "landingPage": {
    "tier": "observed",
    "sessions": 14700,
    "engaged": 9121,
    "submissions": 143
  },
  "paid": {
    "tier": "observed",
    "budgetTotal": 18000,
    "through": "2026-07-31",
    "platforms": [
      {
        "platform": "Google Ads",
        "budget": 6000,
        "flight": "2026-04-28 to 2026-11-24",
        "spend": 7376.62,
        "clicks": 14636,
        "impressions": 665197,
        "sessions": 8490
      },
      {
        "platform": "Microsoft Advertising",
        "budget": 6000,
        "flight": "2026-04-28 to 2026-11-24",
        "spend": 4924.94,
        "clicks": 4504,
        "impressions": 240848,
        "sessions": 4384
      },
      {
        "platform": "LinkedIn Ads",
        "budget": 6000,
        "flight": "2026-03-24 to 2026-11-24",
        "spend": 1924.17,
        "clicks": 585,
        "impressions": 40892,
        "sessions": 920
      }
    ],
    "campaigns": [
      {
        "platform": "Google Ads",
        "campaign": "EDU_fowc_2026",
        "id": "23825879689",
        "spend": 7376.62,
        "clicks": 14636,
        "impressions": 665197,
        "sessions": 8443
      },
      {
        "platform": "Microsoft Advertising",
        "campaign": "EDU_fowc_search",
        "id": "689007335",
        "spend": 4924.94,
        "clicks": 4504,
        "impressions": 240848,
        "sessions": 706
      },
      {
        "platform": "LinkedIn Ads",
        "campaign": "EDU_fowc_doc",
        "id": "1055701594",
        "spend": 1355.54,
        "clicks": 566,
        "impressions": 24763,
        "sessions": 702
      },
      {
        "platform": "LinkedIn Ads",
        "campaign": "fowc_2026",
        "id": "1159466364",
        "spend": 568.63,
        "clicks": 19,
        "impressions": 16129,
        "sessions": 218
      }
    ]
  },
  "email": {
    "tier": "observed",
    "sends": [
      {
        "n": 1,
        "sent": "2026-04",
        "status": "sent",
        "subject": "Empower Your Students with AWS Fundamentals of Welding Curriculum",
        "delivered": 8530,
        "opens": 2463,
        "clicks": 117,
        "unsubs": 43
      },
      {
        "n": 2,
        "sent": "2026-06",
        "status": "sent",
        "subject": "See AWS Fundamentals of Welding Curriculum in Action: Schedule Your Demo Now!",
        "delivered": 6212,
        "opens": 1659,
        "clicks": 190,
        "unsubs": 14
      },
      {
        "n": 3,
        "sent": "after 2026-10-05",
        "status": "scheduled",
        "subject": "FOWC 2026 Email 3"
      },
      {
        "n": 4,
        "sent": "after 2026-11-30",
        "status": "scheduled",
        "subject": "FOWC 2026 Email 4"
      }
    ]
  },
  "delivery": [
    {
      "channel": "Organic social",
      "item": "Awareness post",
      "due": "2026-03",
      "status": "done"
    },
    {
      "channel": "Organic social",
      "item": "Conversion post, video reel",
      "due": "2026-07-30",
      "status": "notStarted"
    },
    {
      "channel": "Traditional",
      "item": "Welding Digest blog post",
      "due": "2026-07-31",
      "status": "notStarted"
    },
    {
      "channel": "Traditional",
      "item": "Welding Journal print ad",
      "due": "2026-08-03 to 2026-08-31",
      "status": "notStarted"
    },
    {
      "channel": "Traditional",
      "item": "Press release",
      "due": "2026-11-16",
      "status": "notStarted"
    },
    {
      "channel": "Traditional",
      "item": "Editorial, how AWS is updating FOWC",
      "due": "2026-12-01",
      "status": "notStarted"
    },
    {
      "channel": "Traditional",
      "item": "Member network announcement",
      "due": "2026-12-08",
      "status": "notStarted"
    }
  ]
};
